config/routes.rb
Rails.application.routes.draw do
  get 'translations/my' => 'translations#my'
  resources :translations
  root 'translations#new'
  devise_for :users
  get 'persons/profile'  
  get 'persons/profile', as: 'user_root'
  get 'persons' => 'persons#index', as: 'all_users'

end

app/models/concerns/blondie_conversions.rb
module BlondieConversions

  @@conversions = {
    '1' => 'ЕДИНИЧКА', '2' => 'ДВОЕЧКА', '3' => 'ТРОЕЧКА',
    '4' => 'ЧЕТВЕРОЧКА', '5' => 'ПЯТЕРОЧКА', '6' => 'ШЕСТЕРОЧКА',
    '7' => 'СЕМЕРОЧКА', '8' => 'ВОСЬМЕРОЧКА', '9' => 'ДЕВЯТОЧКА',
    '0' => 'НОЛИК', 'a' => 'A КАК РУССКАЯ',
    'b' => 'Б КАК ПАЛОЧКА ТАКАЯ И ЖИВОТИК КАК БЫ ВПРАВО СМОТРИТ',
    'c' => 'ЭС КАК РУССКАЯ ЭС', 'd' => 'ДЭ', 'e' => 'Е',
    'f' => 'ЭФ АНГЛИЙСКАЯ', 'g' => 'ГЭ КАК РУССКАЯ Д',
    'h' => 'АШ КАК СТУЛЬЧИК ТАКОЙ', 'i' => 'И С ТОЧЕЧКОЙ',
    'j' => 'ДЖИ КАК КЛЮШКА', 'k' => 'КА РУССКАЯ', 'l' => 'ЭЛЬ ПАЛОЧКА',
    'm' => 'ЭМ', 'n' => 'ЭН КАК РУССКАЯ ПЭ', 'o' => 'О КРУЖОЧКОМ',
    'p' => 'ПЭ КАК РУССКАЯ ЭР', 'q' => 'КУ КАК РУССКАЯ РЭ НАОБОРОТ',
    'r' => 'ЭР КАК Я НАОБОРОТ', 's' => 'ЭС КАК ДОЛЛАР', 't' => 'ТЭ',
    'u' => 'У КАК РУССКАЯ И', 'v' => 'ВЭ КАК ГАЛОЧКА',
    'w' => 'ВЭ КАК ДВЕ ГАЛОЧКИ', 'x' => 'ИКСИК', 'y' => 'ИГРЕК КАК РУССКАЯ У',
    'z' => 'ЗЭТ КАК ЗОРРО',
    ' ' => 'ПРОБЕЛ', '!' => 'ВОСКЛИЦАТЕЛЬНЫЙ ЗНАК', '#' => 'РЕШЕТОЧКА',
    '$' => 'ДОЛЛАР КАК ДОЛЛАР', '%' => 'ПРОЦЕНТИК',
    '&' => 'ВОСЬМЕРКА С ЗАКОРЮЧКОЙ', '(' => 'ЛЕВАЯ СКОБОЧКА',
    ')' => 'ПРАВАЯ СКОБОЧКА', '*' => 'ЗВЕЗДОЧКА', '+' => 'ПЛЮСИК',
    ',' => 'ЗАПЯТАЯ', '-' => 'ТИРЕ', '.' => 'ТОЧЕЧКА',
    '/' => 'КОСАЯ ЧЕРТОЧКА ВПРАВО', ':' => 'ДВОЕТОЧИЕ',
    ';' => 'ТОЧКА С ЗАПЯТОЙ', '<' => 'ЗНАК МЕНЬШЕ', '=' => 'РАВНО',
    '>' => 'ЗНАК БОЛЬШЕ', '?' => 'ВОПРОСИК', '@' => 'СОБАЧКА',
    '\\' => 'КОСАЯ ЧЕРТОЧКА ВЛЕВО', '^' => 'КРЫШКА ОТ ДОМИКА',
    '_' => 'НИЖНЕЕ ПОДЧЕРКИВАНИЕ', '|' => 'ВЕРТИКАЛЬНАЯ ПАЛОЧКА',
    '~' => 'ЛИНИЯ ТАКАЯ ВОЛНИСТАЯ (ОНА НА БУКВЕ Ё)', "\n" => 'НОВАЯ СТРОЧЕЧКА', 
    'а' => 'АЛЕКСАНДР', 'б' => 'БОРИС', 'в' => 'ВЛАДИМИР', 'г' => 'ГЕНАДИЙ',
    'д' => 'ДМИТРИЙ', 'е' => 'ЕЛЕНА', 'ё' => 'Ё РУССКАЯ', 'ж' => 'ЖАННА',
    'з' => 'ЗИНАИДА', 'и' => 'ИЛЬЯ', 'й' => 'И КРАТКАЯ', 'к' => 'КОНСТАНТИН',
    'л' => 'ЛЮДМИЛА', 'м' => 'МАТВЕЙ', 'н' => 'НИКОЛАЙ', 'о' => 'ОЛЕГ',
    'п' => 'ПЕТР', 'р' => 'РУСЛАН', 'с' => 'СЕРГЕЙ', 'т' => 'ТАТЬЯНА',
    'у' => 'УЛЬЯНА', 'ф' => 'ФЕДОР', 'х' => 'ХОСЕ', 'ц' => 'ЦЕЗАРЬ',
    'ч' => 'ЧЕМБЕРЛЕН', 'ш' => 'ШАМИЛЬ', 'щ' => 'ЩАВЕЛЬ', 'ъ' => 'ТВЕРДЫЙ ЗНАК',
    'ы' => 'ЫГОРЬ', 'ь' => 'МЯГКИЙ ЗНАК', 'э' => 'ЭДУАРД', 'ю' => 'ЮЛИЯ',
    'я' => 'ЯРОСЛАВ'
  }

  def get_conversion(c)
    @@conversions.fetch(c, '')
  end
end

app/models/translation.rb
class Translation < ActiveRecord::Base
  include BlondieConversions
  validates :original, presence: true, uniqueness: true
  before_save :translate
  belongs_to :user

  protected

  def strip_comma(s)
    if s.end_with? ','
      s.slice(0, s.length - 1)
    else
      s
    end
  end

  def convert(s)
    translation = ''
    s.each_char do |c|
      translation << "#{get_conversion(UnicodeUtils.downcase(c))}, "
    end
    strip_comma(translation.strip)
  end

  def translate
    self.content = convert(self.original)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :translations, dependent: :nullify
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  before_filter :authenticate_user!, only: :profile

  def profile
  end

  def index
    @users = User.includes(:translations).order(:email).page(params[:page])
  end
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  before_action :set_translation, only: [:show, :destroy]
  before_filter :check_for_admin, only: :destroy
  before_filter :authenticate_user!, only: :my
  before_filter :build_translation, only: :create
  before_filter :set_my_translations, only: :my
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_translation

  # GET /translations
  # GET /translations.json
  def index
    @translations = Translation.order(:created_at).reverse_order.page(params[:page])
  end

  # GET /translations/1
  # GET /translations/1.json
  def show
  end

  # GET /translations/new
  def new
    @translation = Translation.new
  end

  # POST /translations
  # POST /translations.json
  def create
    respond_to do |format|
      if @translation.save
        flash[:success] = 'Перевод создан успешно.'
        format.html { redirect_to @translation }
        format.json { render :show, status: :ok, location: @translation }
      else
        flash[:danger] = 'Что-то пошло не так при создании перевода.'
        format.html { render :new }
        format.json { render json: @translation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /translations/1
  # DELETE /translations/1.json
  def destroy
    @translation.destroy
    respond_to do |format|
      flash[:success] = 'Перевод удалён успешно.'
      format.html { redirect_to translations_url }
      format.json { head :no_content }
    end
  end

  def my
  end

  private

    def check_for_admin
      if not current_user.admin
        logger.error 'Attempt to delete translation #{params[:id]} with no admin permissions'
        flash[:danger] = 'Вы не авторизованы для удаления переводов!'
        redirect_to translations_path
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_translation
      @translation = Translation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def translation_params
      params.require(:translation).permit(:original)
    end

    def invalid_translation
      logger.error 'Attempt to access invalid translation #{params[:id]}'
      flash[:danger] = 'Такого перевода нет!'
      redirect_to translations_path
    end

    def build_translation
      @translation = Translation.new(translation_params)
      @translation.user = current_user
    end

    def set_my_translations
      @translations = current_user.translations.order(:created_at).reverse_order.page(params[:page])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/persons_helper.rb
module PersonsHelper
  def translations_count(user)
    user.translations.length
  end
end

app/helpers/translations_helper.rb
module TranslationsHelper
  def translation_user_email
    if @translation.user
      @translation.user.email
    else
      'Гость'
    end
  end
end

app/views/layouts/_footer.html.slim
footer
  .container
    .row.text-center
      .col-md-12
        = link_to 'GitHub', "https://github.com/DTLuna/skakdollar", class: 'btn btn-info btn-lg'
        a#octocat[href="https://github.com/DTLuna/skakdollar"]
          = image_tag('octocat.png', size: "46")
    .row.text-center
      .col-md-12

app/views/layouts/_header.html.slim
nav.navbar.navbar-default[role="navigation"]
  .container
    .navbar-header
      a.navbar-brand[href="/"]
        | Эс как доллар
      button.navbar-toggle.collapsed[data-toggle="collapse" data-target="#header_menu" aria-expanded="false"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
    - if user_signed_in?
      |  <a href=
      = user_root_path
      | > 
      button.btn.btn-link.navbar-btn[type="button"]
        = current_user.email
    .collapse.navbar-collapse#header_menu
      ul.nav.navbar-nav.navbar-right
        li
          = link_to 'Новый перевод', new_translation_path
        li
          = link_to 'Список пользователей', all_users_path
        li.dropdown
          a.dropdown-toggle[href="#" data-toggle="dropdown"]
            | Меню 
            span.caret
          ul.dropdown-menu[role="menu"]
            - if user_signed_in?
              li
                = link_to 'Выйти', destroy_user_session_path, :method => :delete
            - else
              li
                = link_to 'Войти', new_user_session_path
              li.divider[role="separator"]
              li
                = link_to 'Зарегистрироваться', new_user_registration_path

app/views/layouts/_messages.html.slim
- flash.each do |key, value|
  .alert[class="alert-#{key}"]
    a.close[href="#" data-dismiss="alert"]
      | ×
    ul
      li
        = value
- if notice
  .alert.alert-info
    = notice

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Эс как доллар
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    meta[content="text/html charset=UTF-8", http-equiv="Content-Type"]
    meta[name='viewport' content='width=device-width, initial-scale=']
    = csrf_meta_tags
    = favicon_link_tag("favicon.png")
  body
    = render 'layouts/header'
    #main-container.container
      .row
        .col-md-3
          h1
            | Эс как доллар
          = image_tag('blonde.jpg', class: 'img-rounded')
          = image_tag('privetiki.png', class: 'img-rounded')
          p
            | Этот сайт мы придумали специально для тебя! Он поможет тебе продиктовать подругам адрес твоей странички, электронную почту и разные другие адреса в интернете!
          p
            strong
              | Жми кнопочку «Новый перевод»!
        .col-md-9
          = render 'layouts/messages'
          = yield
        hr
    =render 'layouts/footer'

app/views/persons/index.html.slim
ul.nav.nav-tabs.nav-justified[role="tablist"]
  li
    = link_to 'Все переводы', translations_path
  li
    = link_to 'Новый перевод', new_translation_path
  li.active
    = link_to 'Список пользователей', all_users_path
  - if current_user
    li
      = link_to 'Мои переводы', translations_my_path
h1
  | Пользователи
- if @users.length == 0
  p
    | Пока что никто не зарегистрировался. Стань первым пользователем! ;)
- else
  table.table.table-hover
    thead
      tr
        th
          | E-mail
        th
          | Переводов создано
        th
          | Время регистрации
        th[colspan="3"]
    tbody
      - @users.each do |user|
        - if user == current_user
          tr.info

        - else
          tr

        td
          = user.email
        td
          = translations_count(user)
        td
          = user.created_at
  div
    = paginate @users

app/views/persons/profile.html.slim
p#notice
  = notice
p
  strong
    | E-mail:
  = current_user.email
p
  strong
    | Зарегистрирован:
  = current_user.created_at
p
  strong
    | Переводов создано: 
  = current_user.translations.length
= link_to translations_path, class: 'btn btn-primary' do
  i.glyphicon.glyphicon-arrow-left
  | Ко всем переводам 
= link_to translations_my_path, class: 'btn btn-success' do
  i.glyphicon.glyphicon-arrow-right
  | К моим переводам 
= link_to 'Редактировать профиль', edit_user_registration_path, class: 'btn btn-default'
= link_to 'Выйти', destroy_user_session_path, :method => :delete, class: 'btn btn-default'

app/views/translations/_form.html.slim
= form_for(@translation, html: {class: 'form-horizontal'}) do |f|
  - if @translation.errors.any?
    .alert.alert-danger[role="alert"]
      h2
        = pluralize(@translation.errors.count, "error")
        |  prohibited this translation from being saved:
      ul
        - @translation.errors.full_messages.each do |message|
          li
            = message
  p
    | Просто скопируй адрес в поле внизу и нажми на кнопочку «ПЕРЕВОД!»!
  .field.form-group
    = f.label 'ТВОЙ АДРЕС', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_area :original, class: 'form-control'
  .actions.form-group
    .col-sm-offset-2.col-sm-10
      = f.submit 'ПЕРЕВОД!', class: 'btn btn-success btn-lg'

app/views/translations/_translations_table.html.slim
- if @translations.length == 0
  p
    | Пока что переводов нет. Добавь новый! ;)
- else
  table.table.table-hover
    thead
      tr
        th
          | Адрес
        th
          | Как читать ;)
        th[colspan="3"]
    tbody
      - @translations.each do |translation|
        tr
          td
            = truncate(translation.original)
          td
            = truncate(translation.content, length: 75)
          td
            = link_to translation, class: 'btn btn-primary btn-md' do
              i.glyphicon.glyphicon-arrow-right
              | Показать 
          - if current_user.try(:admin?)
            td
              = link_to translation, method: :delete, data: { confirm: 'Вы уверены?' }, class: 'btn btn-danger btn-md' do
                i.glyphicon.glyphicon-trash
                | Удалить 
  div
    = paginate @translations
.row
  .col-md-12
    = link_to new_translation_path, class: 'btn btn-success btn-lg' do
      i.glyphicon.glyphicon-plus
      | Новый перевод 

app/views/translations/index.html.slim
ul.nav.nav-tabs.nav-justified[role="tablist"]
  li.active
    = link_to 'Все переводы', translations_path
  li
    = link_to 'Новый перевод', new_translation_path
  li
    = link_to 'Список пользователей', all_users_path
  - if current_user
    li
      = link_to 'Мои переводы', translations_my_path
h1
  | Все переводы =)
= render 'translations_table'

app/views/translations/my.html.slim
ul.nav.nav-tabs[role="tablist"]
  li
    = link_to 'Все переводы', translations_path
  li
    = link_to 'Новый перевод', new_translation_path
  li
    = link_to 'Список пользователей', all_users_path
  - if current_user
    li.active
      = link_to 'Мои переводы', translations_my_path
h1
  | Твои переводы ;)
= render 'translations_table'

app/views/translations/new.html.slim
ul.nav.nav-tabs.nav-justified[role="tablist"]
  li
    = link_to 'Все переводы', translations_path
  li.active
    = link_to 'Новый перевод', new_translation_path
  li
    = link_to 'Список пользователей', all_users_path
  - if current_user
    li
      = link_to 'Мои переводы', translations_my_path
h1
  | Новый перевод
= render 'form'
= link_to translations_path, class: 'btn btn-primary' do
  i.glyphicon.glyphicon-arrow-left
  | Ко всем переводам 

app/views/translations/show.html.slim
ul.nav.nav-tabs.nav-justified[role="tablist"]
  li
    = link_to 'Все переводы', translations_path
  li
    = link_to 'Новый перевод', new_translation_path
  li
    = link_to 'Список пользователей', all_users_path
  - if current_user
    li
      = link_to 'Мои переводы', translations_my_path
p
  strong
    | Адрес:
  = @translation.original
p
  strong
    | Читай так;): 
  br
  = @translation.content
p
  strong
    | Создал:
  = translation_user_email
p
  strong
    | ЧМОКИ :-*
= link_to translations_path, class: 'btn btn-primary btn' do
  i.glyphicon.glyphicon-arrow-left
  | Ко всем переводам 